/**
 * Build-time helper: embeds packages/db/src/schema.sql into a TypeScript
 * module so the serverless function bundle carries the schema without
 * relying on fs reads of the monorepo source tree at runtime.
 *
 * Runs automatically via the `prebuild` npm lifecycle hook before
 * `next build`. Output is gitignored and regenerated on every build.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const schemaPath = join(here, "..", "..", "..", "packages", "db", "src", "schema.sql");
const outPath = join(here, "..", "lib", "schema-embedded.ts");

const sql = readFileSync(schemaPath, "utf8");
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(
  outPath,
  `/**\n * AUTO-GENERATED by apps/web/scripts/embed-schema.mjs — do not edit.\n * Source: packages/db/src/schema.sql (embedded at build time).\n */\nexport const SCHEMA_SQL: string = ${JSON.stringify(sql)};\n`
);
console.log(`[embed-schema] wrote ${outPath} (${sql.length} chars)`);
